/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 maze.glb 
Author: neosearch (https://sketchfab.com/neosearch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/labyrinth-map-for-game-12e8e2a964f34b0c89eb315ae57b9b26
Title: labyrinth map for game
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function MazeModel(props) {
  const { nodes, materials } = useGLTF("models/maze.glb");
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials["Material.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/maze.glb");
